---
- name: Dump Variables
  template:
    src: "dump_vars.j2"
    dest: "/tmp/ansible_variables"
  tags:
    - Information

- name: Fetch Variables
  fetch:
    src: "/tmp/ansible_variables"
    dest: "remote_files/{{ inventory_hostname }}"
  tags:
    - Information

- include: "{{ ansible_distribution }}.yml"
  when: update is not defined
  
- include: "update.yml"
  when: update is defined
