galaxy_info:
  author: Paul Lyon <pmlyon@gmail.com>
  description: Setup and configure Docker on REH/CentOS, Debian/Ubuntu, Gentoo, and Archlinux using the distribution's repositories.
  issue_tracker_url: https://github.com/the-paulus/ansible/issues
  license: GPLv3
  min_ansible_version: 1.2
  github_branch: master
  platforms:
    - name: Fedora
      versions:
        - 25
        - 26
    - name: CentOS
      versions:
        - 7
    - name: RedHat
      versions:
        - 7
    - name: Debian
      versions:
        - 6
        - 7
        - 8
    - name: Ubuntu
      versions:
        -
    - name: Gentoo
      versions:
        - all


  galaxy_tags: [
  RedHat
  Gentoo
  Archlinux
  Ubuntu
  Debian
  Docker
  ]
    # List tags for your role here, one per line. A tag is a keyword that describes
    # and categorizes the role. Users find roles by searching for tags. Be sure to
    # remove the '[]' above, if you add tags to this list.
    #
    # NOTE: A tag is limited to a single word comprised of alphanumeric characters.
    #       Maximum 20 tags per role.

dependencies: []
  # List your role dependencies here, one per line. Be sure to remove the '[]' above,
  # if you add dependencies to this list.
